### ISSUE TITLE
"unsafe-eval" in getGlobalObject

### ISSUE THREAD

**Issue by destroytoday** [cocopon/tweakpane#361]
Hi! The `new Function('return this')();` code in the `getGlobalObject` method throws an "unsafe-eval" error for CSPs with `script-src 'self'`. I was able to get around this in the init of TweakPane by providing `document` in the config, but when the color blade calls `isBrowser`, it directly calls `getGlobalObject` instead of using the config document.

Maybe there’s a way of getting the global object without using eval?

**Comment by awelles** [comment]
Hi,

I'm not too familiar with tweakpane's codebase, but was doing this recently. I ended up with this:

```js
function getGlobalObject() {
  
  Object.defineProperty(Object.prototype, '__$$te$$mp$$__', {
    get: function() { return this; },
    configurable: true
    });
    
  const globalObject = __$$te$$mp$$__;

  delete Object.prototype.__$$te$$mp$$__;

  return globalObject;
}
```

**Comment by cocopon** [comment]
Thank you for reporting the issue! Fixed in #363, please wait for the next release.

**Comment by destroytoday** [comment]
@cocopon Thank you!!

**Comment by cocopon** [comment]
Released the latest version 3.0.7.

**Comment by jsantos98** [comment]
I'm still getting this error in Electron, using version 3.0.7.

Not sure if I'm doing something wrong!

**Comment by jsantos98** [comment]
Nevermind... reread @destroytoday initial comment and provided the missing document
`new Pane({
           document: window.document
         });`

The eval error went away!
